export interface TableField {
  name: string;
  label: string;
  type: 'string' | 'number' | 'boolean' | 'enum' | 'datetime' | 'json';
  isId?: boolean;
  required?: boolean;
  options?: string[];
  description?: string;
}

export interface TableDefinition {
  name: string;
  displayName: string;
  category: 'Core & RBAC' | 'Households & Members' | 'Catalog & SOPs' | 'Billing & Wallets' | 'Operations' | 'Clinical & Vitals' | 'Emergency';
  iconName: string;
  primaryKey: string;
  fields: TableField[];
}

export const TABLE_DEFINITIONS: Record<string, TableDefinition> = {
  User: {
    name: 'User',
    displayName: 'Users & Identity',
    category: 'Core & RBAC',
    iconName: 'User',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'User ID', type: 'string', isId: true, required: true },
      { name: 'name', label: 'Full Name', type: 'string', required: true },
      { name: 'phone', label: 'Phone Number', type: 'string', required: true },
      { name: 'email', label: 'Email Address', type: 'string' },
      { name: 'isActive', label: 'Account Active', type: 'boolean', required: true },
      { name: 'createdAt', label: 'Created At', type: 'datetime' },
      { name: 'updatedAt', label: 'Updated At', type: 'datetime' },
    ],
  },
  UserRoleMapping: {
    name: 'UserRoleMapping',
    displayName: 'User Role Mappings',
    category: 'Core & RBAC',
    iconName: 'Shield',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Mapping ID', type: 'string', isId: true, required: true },
      { name: 'userId', label: 'User ID (FK)', type: 'string', required: true },
      { name: 'role', label: 'Role Type', type: 'enum', options: ['ADMIN', 'OPS_MANAGER', 'DISPATCHER', 'CARE_OFFICER', 'DOCTOR', 'NURSE', 'PHYSIOTHERAPIST', 'FAMILY_PRIMARY_NRI', 'FAMILY_PRIMARY_LOCAL', 'FAMILY_VIEWER', 'ELDER'], required: true },
      { name: 'householdId', label: 'Household ID (FK)', type: 'string' },
      { name: 'createdAt', label: 'Created At', type: 'datetime' },
    ],
  },
  Household: {
    name: 'Household',
    displayName: 'Households',
    category: 'Households & Members',
    iconName: 'Home',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Household ID', type: 'string', isId: true, required: true },
      { name: 'name', label: 'Household Name', type: 'string', required: true },
      { name: 'city', label: 'City', type: 'string', required: true },
      { name: 'addressLine', label: 'Address Line', type: 'string', required: true },
      { name: 'postalCode', label: 'Postal Code', type: 'string', required: true },
      { name: 'primaryContactPhone', label: 'Primary Contact Phone', type: 'string', required: true },
      { name: 'timeZone', label: 'Time Zone', type: 'string', required: true },
      { name: 'careOfficerId', label: 'Assigned Care Officer ID', type: 'string' },
      { name: 'createdAt', label: 'Created At', type: 'datetime' },
    ],
  },
  Member: {
    name: 'Member',
    displayName: 'Household Members (Seniors)',
    category: 'Households & Members',
    iconName: 'Users',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Member ID', type: 'string', isId: true, required: true },
      { name: 'householdId', label: 'Household ID (FK)', type: 'string', required: true },
      { name: 'firstName', label: 'First Name', type: 'string', required: true },
      { name: 'lastName', label: 'Last Name', type: 'string', required: true },
      { name: 'phone', label: 'Phone Number', type: 'string' },
      { name: 'relationship', label: 'Relationship', type: 'string', required: true },
      { name: 'gender', label: 'Gender', type: 'string' },
      { name: 'abhaNumber', label: 'ABHA Number', type: 'string' },
      { name: 'abhaStatus', label: 'ABHA Status', type: 'enum', options: ['NOT_LINKED', 'PENDING', 'LINKED', 'FAILED'], required: true },
      { name: 'createdAt', label: 'Created At', type: 'datetime' },
    ],
  },
  IceProfile: {
    name: 'IceProfile',
    displayName: 'Emergency ICE Profiles',
    category: 'Households & Members',
    iconName: 'HeartPulse',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'ICE ID', type: 'string', isId: true, required: true },
      { name: 'memberId', label: 'Senior Member ID (FK)', type: 'string', required: true },
      { name: 'bloodGroup', label: 'Blood Group', type: 'string' },
      { name: 'allergies', label: 'Allergies (JSON)', type: 'json' },
      { name: 'chronicConditions', label: 'Chronic Conditions (JSON)', type: 'json' },
      { name: 'currentMedications', label: 'Current Medications (JSON)', type: 'json' },
      { name: 'preferredHospitalName', label: 'Preferred Hospital Name', type: 'string' },
      { name: 'preferredHospitalPhone', label: 'Preferred Hospital Phone', type: 'string' },
      { name: 'active', label: 'Active Status', type: 'boolean', required: true },
      { name: 'lastReviewedAt', label: 'Last Reviewed At', type: 'datetime' },
    ],
  },
  ServiceCatalog: {
    name: 'ServiceCatalog',
    displayName: '90-Service Catalog',
    category: 'Catalog & SOPs',
    iconName: 'BookOpen',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Service ID', type: 'string', isId: true, required: true },
      { name: 'serviceNumber', label: 'Service #', type: 'number', required: true },
      { name: 'code', label: 'Service Code', type: 'string', required: true },
      { name: 'name', label: 'Service Name', type: 'string', required: true },
      { name: 'category', label: 'Category', type: 'enum', options: ['A_EMERGENCY', 'B_PRIMARY_CARE', 'C_DIAGNOSTICS', 'D_MEDICATION', 'E_THERAPY', 'F_HIGH_DEPENDENCY', 'G_RECORDS_INSURANCE', 'H_DAILY_LIVING', 'I_FINANCIAL_LEGAL', 'J_MOBILITY_TRAVEL', 'K_COMPANIONSHIP', 'L_FAMILY_LAYER'], required: true },
      { name: 'unitPricePaise', label: 'Unit Price (Paise)', type: 'number', required: true },
      { name: 'slaMinutes', label: 'SLA (Minutes)', type: 'number' },
      { name: 'isPayPerUseOnly', label: 'Pay-Per-Use Only', type: 'boolean' },
    ],
  },
  PlanTier: {
    name: 'PlanTier',
    displayName: 'Subscription Plan Tiers',
    category: 'Catalog & SOPs',
    iconName: 'Layers',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Tier ID', type: 'string', isId: true, required: true },
      { name: 'name', label: 'Tier Name', type: 'enum', options: ['KAVACH', 'SAHARA', 'SAMPOORNA', 'NIVAS'], required: true },
      { name: 'annualPricePaise', label: 'Annual Price (Paise)', type: 'number', required: true },
      { name: 'description', label: 'Tier Description', type: 'string', required: true },
    ],
  },
  PlanQuota: {
    name: 'PlanQuota',
    displayName: 'Plan Quotas',
    category: 'Catalog & SOPs',
    iconName: 'Percent',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Quota ID', type: 'string', isId: true, required: true },
      { name: 'planTierId', label: 'Plan Tier ID (FK)', type: 'string', required: true },
      { name: 'serviceCatalogId', label: 'Service Catalog ID (FK)', type: 'string', required: true },
      { name: 'includedUnitsYear', label: 'Included Units / Year', type: 'number', required: true },
      { name: 'isUnlimited', label: 'Unlimited Quota', type: 'boolean', required: true },
    ],
  },
  SopTemplate: {
    name: 'SopTemplate',
    displayName: 'Dynamic SOP Templates',
    category: 'Catalog & SOPs',
    iconName: 'FileText',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'SOP ID', type: 'string', isId: true, required: true },
      { name: 'serviceCatalogId', label: 'Service Catalog ID (FK)', type: 'string', required: true },
      { name: 'version', label: 'Version #', type: 'number', required: true },
      { name: 'title', label: 'SOP Title', type: 'string', required: true },
      { name: 'description', label: 'Description', type: 'string', required: true },
      { name: 'jsonSchema', label: 'Checklist Schema (JSON)', type: 'json', required: true },
      { name: 'active', label: 'Active Version', type: 'boolean', required: true },
    ],
  },
  Subscription: {
    name: 'Subscription',
    displayName: 'Household Subscriptions',
    category: 'Billing & Wallets',
    iconName: 'CreditCard',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Subscription ID', type: 'string', isId: true, required: true },
      { name: 'householdId', label: 'Household ID (FK)', type: 'string', required: true },
      { name: 'planTierId', label: 'Plan Tier ID (FK)', type: 'string', required: true },
      { name: 'status', label: 'Subscription Status', type: 'string', required: true },
      { name: 'startDate', label: 'Start Date', type: 'datetime', required: true },
      { name: 'endDate', label: 'End Date', type: 'datetime', required: true },
      { name: 'autoRenew', label: 'Auto Renew', type: 'boolean', required: true },
    ],
  },
  SubscriptionQuotaLedger: {
    name: 'SubscriptionQuotaLedger',
    displayName: 'Subscription Quota Ledgers',
    category: 'Billing & Wallets',
    iconName: 'ListOrdered',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Ledger ID', type: 'string', isId: true, required: true },
      { name: 'subscriptionId', label: 'Subscription ID (FK)', type: 'string', required: true },
      { name: 'serviceCatalogId', label: 'Service Catalog ID (FK)', type: 'string', required: true },
      { name: 'totalAllocated', label: 'Total Allocated', type: 'number', required: true },
      { name: 'usedUnits', label: 'Used Units', type: 'number', required: true },
      { name: 'remainingUnits', label: 'Remaining Units', type: 'number', required: true },
    ],
  },
  Wallet: {
    name: 'Wallet',
    displayName: 'Prepaid Care Wallets',
    category: 'Billing & Wallets',
    iconName: 'Wallet',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Wallet ID', type: 'string', isId: true, required: true },
      { name: 'householdId', label: 'Household ID (FK)', type: 'string', required: true },
      { name: 'balancePaise', label: 'Balance (Paise)', type: 'number', required: true },
      { name: 'currency', label: 'Currency', type: 'string', required: true },
      { name: 'updatedAt', label: 'Updated At', type: 'datetime' },
    ],
  },
  WalletTransaction: {
    name: 'WalletTransaction',
    displayName: 'Wallet Transactions',
    category: 'Billing & Wallets',
    iconName: 'Receipt',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Transaction ID', type: 'string', isId: true, required: true },
      { name: 'walletId', label: 'Wallet ID (FK)', type: 'string', required: true },
      { name: 'amountPaise', label: 'Amount (Paise)', type: 'number', required: true },
      { name: 'type', label: 'Transaction Type', type: 'enum', options: ['CREDIT', 'HOLD', 'DEBIT', 'REFUND'], required: true },
      { name: 'referenceType', label: 'Reference Type', type: 'string', required: true },
      { name: 'description', label: 'Description', type: 'string', required: true },
      { name: 'createdAt', label: 'Created At', type: 'datetime' },
    ],
  },
  ServiceExecution: {
    name: 'ServiceExecution',
    displayName: 'Service Executions & Visits',
    category: 'Operations',
    iconName: 'CalendarCheck',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Execution ID', type: 'string', isId: true, required: true },
      { name: 'householdId', label: 'Household ID (FK)', type: 'string', required: true },
      { name: 'memberId', label: 'Member ID (FK)', type: 'string', required: true },
      { name: 'serviceCatalogId', label: 'Service Code (FK)', type: 'string', required: true },
      { name: 'assignedToUserId', label: 'Assigned User ID', type: 'string' },
      { name: 'status', label: 'Execution Status', type: 'enum', options: ['SCHEDULED', 'EN_ROUTE', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED'], required: true },
      { name: 'scheduledAt', label: 'Scheduled At', type: 'datetime', required: true },
      { name: 'isDrill', label: 'Is Dry Run Drill', type: 'boolean' },
      { name: 'totalChargePaise', label: 'Total Charge (Paise)', type: 'number' },
    ],
  },
  ClinicalConsult: {
    name: 'ClinicalConsult',
    displayName: 'Clinical Consultations',
    category: 'Clinical & Vitals',
    iconName: 'Stethoscope',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Consult ID', type: 'string', isId: true, required: true },
      { name: 'serviceExecutionId', label: 'Execution ID (FK)', type: 'string', required: true },
      { name: 'memberId', label: 'Member ID (FK)', type: 'string', required: true },
      { name: 'doctorUserId', label: 'Doctor User ID (FK)', type: 'string', required: true },
      { name: 'consultType', label: 'Consult Type', type: 'enum', options: ['DOCTOR_HOME_VISIT', 'GP_TELECONSULT', 'SPECIALIST_TELECONSULT'], required: true },
      { name: 'chiefComplaint', label: 'Chief Complaint', type: 'string', required: true },
      { name: 'clinicalNotes', label: 'Clinical Notes', type: 'string', required: true },
      { name: 'diagnosisIcd10', label: 'ICD-10 Diagnosis', type: 'string' },
    ],
  },
  Prescription: {
    name: 'Prescription',
    displayName: 'Prescriptions',
    category: 'Clinical & Vitals',
    iconName: 'Pill',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Prescription ID', type: 'string', isId: true, required: true },
      { name: 'clinicalConsultId', label: 'Consult ID (FK)', type: 'string', required: true },
      { name: 'memberId', label: 'Member ID (FK)', type: 'string', required: true },
      { name: 'doctorUserId', label: 'Doctor User ID (FK)', type: 'string', required: true },
      { name: 'medicationItems', label: 'Medications (JSON)', type: 'json', required: true },
      { name: 'pdfUrl', label: 'Prescription PDF URL', type: 'string' },
      { name: 'issuedAt', label: 'Issued At', type: 'datetime' },
    ],
  },
  VitalsReading: {
    name: 'VitalsReading',
    displayName: 'Vitals Readings',
    category: 'Clinical & Vitals',
    iconName: 'Activity',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Reading ID', type: 'string', isId: true, required: true },
      { name: 'memberId', label: 'Member ID (FK)', type: 'string', required: true },
      { name: 'systolicBp', label: 'Systolic BP (mmHg)', type: 'number' },
      { name: 'diastolicBp', label: 'Diastolic BP (mmHg)', type: 'number' },
      { name: 'bloodGlucoseMgDl', label: 'Blood Glucose (mg/dL)', type: 'number' },
      { name: 'fastingState', label: 'Fasting State', type: 'string' },
      { name: 'pulseBpm', label: 'Pulse (bpm)', type: 'number' },
      { name: 'spo2Percent', label: 'SpO2 (%)', type: 'number' },
      { name: 'isAbnormal', label: 'Abnormal Flag', type: 'boolean' },
      { name: 'recordedAt', label: 'Recorded At', type: 'datetime' },
    ],
  },
  EmergencyEvent: {
    name: 'EmergencyEvent',
    displayName: 'Emergency Events',
    category: 'Emergency',
    iconName: 'ShieldAlert',
    primaryKey: 'id',
    fields: [
      { name: 'id', label: 'Incident ID', type: 'string', isId: true, required: true },
      { name: 'householdId', label: 'Household ID (FK)', type: 'string', required: true },
      { name: 'memberId', label: 'Member ID (FK)', type: 'string', required: true },
      { name: 'initiatedByPhone', label: 'Initiated By Phone', type: 'string', required: true },
      { name: 'severity', label: 'Severity', type: 'enum', options: ['CRITICAL', 'URGENT', 'ROUTINE'], required: true },
      { name: 'status', label: 'Status', type: 'enum', options: ['OPEN', 'DISPATCHED', 'AT_SCENE', 'HOSPITALIZED', 'RESOLVED', 'FALSE_ALARM'], required: true },
      { name: 'outcomeSummary', label: 'Outcome Summary', type: 'string' },
      { name: 'createdAt', label: 'Created At', type: 'datetime' },
    ],
  },
};
