module.exports = {
  apps: [
    {
      name: 'poco-api',
      cwd: './apps/api',
      script: 'dist/main.js',
      node_args: '--max-old-space-size=512',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        DATABASE_URL: 'postgresql://postgres:password123@localhost:5432/pocoeldercare?schema=public',
        REDIS_URL: 'redis://localhost:6379',
      },
      instances: 1,
      autorestart: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      exp_backoff_restart_delay: 200,
      max_memory_restart: '400M',
    },
    {
      name: 'poco-ops-crm',
      cwd: './apps/ops-crm',
      script: 'pnpm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      autorestart: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      max_memory_restart: '500M',
    },
    {
      name: 'poco-family-portal',
      cwd: './apps/family-portal',
      script: 'pnpm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      autorestart: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      max_memory_restart: '500M',
    },
    {
      name: 'poco-field-app',
      cwd: './apps/field-app',
      script: 'pnpm',
      args: 'preview',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      max_memory_restart: '300M',
    },
    {
      name: 'poco-db-admin',
      cwd: './apps/db-admin',
      script: 'pnpm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
      },
      autorestart: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      max_memory_restart: '500M',
    },
  ],
};
