/**
 * Supported integration partner codes.
 */
export enum PartnerCode {
  RAZORPAY = 'RAZORPAY',
  EXOTEL = 'EXOTEL',
  POCOCARE = 'POCOCARE',
  POCOCARE_EMR = 'POCOCARE_EMR',
  WEARABLE_IOT = 'WEARABLE_IOT',
  ABHA = 'ABHA',
  WHATSAPP = 'WHATSAPP',
  ONE_MG = 'ONE_MG',
  APOLLO_1MG = 'APOLLO_1MG',
  ORANGE_LABS = 'ORANGE_LABS',
  HEALTH_SERVICES = 'HEALTH_SERVICES',
  MAX_HEALTHCARE = 'MAX_HEALTHCARE',
  INSTAMART = 'INSTAMART',
  SWIGGY = 'SWIGGY',
  URBAN_COMPANY = 'URBAN_COMPANY',
  OLA = 'OLA',
  UBER_CARE = 'UBER_CARE',
  PORTER_LOGISTICS = 'PORTER_LOGISTICS'
}

export const PARTNER_CODES = Object.values(PartnerCode) as readonly PartnerCode[];

/**
 * Partner service category classification.
 */
export enum PartnerCategory {
  PAYMENT = 'PAYMENT',
  TELEPHONY = 'TELEPHONY',
  HEALTHCARE_EMR = 'HEALTHCARE_EMR',
  IOT_DEVICE = 'IOT_DEVICE',
  PHARMACY = 'PHARMACY',
  HOSPITAL = 'HOSPITAL',
  TRANSPORT = 'TRANSPORT',
  LOGISTICS = 'LOGISTICS',
  DIAGNOSTICS = 'DIAGNOSTICS',
  MESSAGING = 'MESSAGING',
  QUICK_COMMERCE = 'QUICK_COMMERCE',
  MEAL_DELIVERY = 'MEAL_DELIVERY',
  HOME_SERVICES = 'HOME_SERVICES'
}
